services:
  browserless:
    image: browserless/chrome
    ports:
      - 3000:3000
    environment:
      MAX_CONCURRENT_SESSIONS: 10
      CONNECTION_TIMEOUT: -1
      TIMEOUT: -1
      KEEP_ALIVE: "true"
      DATA_DIR: /user_data
    volumes:
      - ./.user_data:/user_data
    networks:
      - scraper

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-deepseek_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scraper

networks:
  scraper:
    external: true

volumes:
  postgres_data:
