services:
  browserless:
    image: browserless/chrome
    ports:
      - 3000:3000
    environment:
      MAX_CONCURRENT_SESSIONS: 5
      CONNECTION_TIMEOUT: 60000
    networks:
      - scraper

networks:
  scraper:
    external: true
