services:
  browserless:
    image: browserless/chrome
    ports:
      - 3000:3000
    environment:
      MAX_CONCURRENT_SESSIONS: 10
      CONNECTION_TIMEOUT: -1
      TIMEOUT: -1
      KEEP_ALIVE: "true"
      DATA_DIR: /user_data
    volumes:
      - ./.user_data:/user_data
    networks:
      - scraper

networks:
  scraper:
    external: true
